import numpy as np
import pandas as pd
from scipy.stats import gaussian_kde
from scipy.ndimage import gaussian_filter1d
from scipy.signal import find_peaks


# Input: CSV file generated by PosturalFeatureExtraction.py
FILE_PATH = "parameters.csv"
FRAME_RATE = 12
BIN_SIZE_MIN = 5


parameters_df = pd.read_csv(FILE_PATH)

frames_per_bin = FRAME_RATE * 60 * BIN_SIZE_MIN
binned_speed = parameters_df["Body Speed"].groupby(
    np.arange(len(parameters_df)) // frames_per_bin
).mean()

kde = gaussian_kde(binned_speed, bw_method="scott")
x_range = np.linspace(binned_speed.min(), binned_speed.max(), 1000)
kde_values = kde(x_range)
smoothed_kde = gaussian_filter1d(kde_values, sigma=1)

kde_diff = np.diff(smoothed_kde)
peaks, _ = find_peaks(-kde_diff)

threshold_index = peaks[0] if peaks.size > 0 else len(x_range) // 2
threshold_value = x_range[threshold_index]
